### PR TITLE
Added additional useful utilities.

### PR DESCRIPTION
**Pull request by qcr86**
Added some utilities that may be of use, especially later for smoothing movement for the entities if it is used.

### CODE REVIEW

**Review by DuckyShine004 — APPROVED** [review]
I've reviewed the changes and it LGTM! :+1: 

A possible optimization which could reduce the initial load time (although not by a lot), would be to create a better height map function, which I will hopefully address in another issue.

**Comment by DuckyShine004** [comment]
> Added some utilities that may be of use, especially later for smoothing movement for the entities if it is used.

Hello! Before I merge the PR, could you please create a new branch and merge your changes there first? Thanks.

**Comment by qcr86** [comment]
Done. I added additional pull request for it specifically, please let me know if I did it wrong however, I had some issues when attempting to do so.

**Comment by DuckyShine004** [comment]
Merged PR #64 with the same changes (Resolves #63) . The difference here is that, PR #64 safely merges branch `x` onto `main`. This will ensure stability of the `main` branch.

**Pull request closed without merging**
